name: Build

on:
    push:
        tags:
            - "v*.*.*"

permissions:
    contents: write

jobs:
    build:
        name: Building

        strategy:
            matrix:
                include:
                    - os: macos-latest
                      arch: arm64
                    - os: ubuntu-latest
                      arch: x64
                    - os: windows-latest
                      arch: x64

        runs-on: ${{ matrix.os }}

        steps:
            - name: Doing checkout
              uses: actions/checkout@v6

            - name: Setting up Python
              uses: actions/setup-python@v6
              with:
                  python-version: 3.12
                  architecture: ${{ matrix.arch }}

            - name: Installing dependencies
              run: |
                  pip install uv
                  uv export --no-dev -o requirements.txt
                  pip install -r requirements.txt

            - name: Compiling
              uses: Nuitka/Nuitka-Action@v1.4
              with:
                  script-name: src
                  mode: onefile
                  python-flag: -m

            - name: Preparing binary
              shell: bash
              run: |
                  mkdir -p dist
                  mkdir -p dist.unpacked

                  VERSION="${GITHUB_REF_NAME#v}"
                  OS="$(echo '${{ runner.os }}' | tr '[:upper:]' '[:lower:]')"
                  ARCH="${{ matrix.arch }}"

                  if [ "${{ runner.os }}" = "Windows" ]; then
                    cp "build/src.exe" "dist.unpacked/website_archiver.exe"
                    powershell.exe -Command "
                    Compress-Archive -Path dist.unpacked\* \
                      -DestinationPath dist\WebsiteArchiver-${VERSION}-${OS}-${ARCH}.zip \
                      -Force
                    "
                  else
                    cp "build/src.bin" "dist.unpacked/website_archiver"
                    tar -czf "dist/WebsiteArchiver-${VERSION}-${OS}-${ARCH}.tar.gz" dist.unpacked/*
                  fi

            - name: Uploading artifacts
              uses: actions/upload-artifact@v7
              with:
                  name: WebsiteArchiver-${{ runner.os }}-${{ matrix.arch }}
                  path: dist/*

    release:
        name: Release
        needs: build

        runs-on: ubuntu-latest

        steps:
            - name: Downloading artifacts
              uses: actions/download-artifact@v8
              with:
                  path: dist

            - name: Creating release
              uses: softprops/action-gh-release@v3
              with:
                  files: dist/**/*
                  make_latest: true
                  generate_release_notes: true
